#!/bin/bash

#
# aprspass
# python script wrapper for aprspass.py
#
# Version 1.0a
#
# Steve de Bode - KQ4ZCI - December 2025
#

# Check Parameters
if [ "$#" -ne "1" ]; then
  printf '\nIncorrect syntax\n\n %s <callsign>\n\n' "${0##*/}" >&2
  exit 1
fi

aprspass=$(python3 aprspass.py "$1" )

printf  '\nThe APRS password for callsign %s is: %s\n\n' "$1" "$aprspass"
