#!/bin/bash

: <<'END'
checkcall
Get FCC Information by ham Callsign

Input:	callsign
Output: formatted FCC Information
Version 1.0a

Steve de Bode - KQ4ZCI - December 2025

Input:	callsign
Output: none - interactive
END

# Check Parameters
if [ "$#" -ne "1" ]; then
  printf '\nIncorrect syntax\n\n %s <callsign>\n\n' "${0##*/}" >&2
  exit 1
fi

# Get Home QTH & Check Valid
qth=$(curl -s "https://api.hamdb.org/v1/$1/csv/$1")
IFS=',' read -r callsign class expiry grid lat lon licstat forename initial surname suffix street town state zip country <<< "$qth"

if [ "$callsign" != "${1^^}" ]; then
 printf '\nThe Callsign \"%s\" is either invalid or not found, please check and try again.\n\n' "$1"
 exit 1
fi

fullname="$forename $initial $surname $suffix"; fullname=$(echo "$fullname" | xargs)
address="$street, $town, $state $zip $country"

# Convert License Class
case "$class" in "T") class="Technician" ;; "G") class="General" ;; "E") class="Extra" ;; "N") class="Novice" ;; "A") class="Advanced" ;; *) class="Station Callsign" ;; esac

# Convert License Status
case "$licstat" in "A") licstat="Active" ;; "E") licstat="Expired" ;; "P") licstat="Pending" ;; *) licstat="Unknown" ;; esac

printf '\nThe details held by the FCC for %s are:\n\n' "$callsign"
printf 'License:\t%s - Expiry %s (%s)\nName:\t\t%s\nAddress:\t%s\nCoordinates:\tGrid: %s Latitude: %s Longitude %s\n\n' "$class" "$expiry" "$licstat" "$fullname" "$address" "$grid" "$lat" "$lon"
