#!/usr/bin/env bash

: <<'END'
dhremove
DigiHub uninstallation

Version 1.0a

Steve de Bode - KQ4ZCI - December 2025

Input:	none
Output: none - interactive
END

# Uninstallation warning 
printf '\nThis action will completely remove DigiHub, continue (Y/n)? '; read -n1 -r response
case $response in Y|y) printf '\nRemoving DigiHub.\n';; N|n) printf '\nUninstall aborted.\n\n'; exit 0 ;; *) printf '\nInvalid response, please select (Y/n)\n' ;; esac

HomePath="/home/$USER"
deactivate >/dev/null 2>&1
cd "$HomePath"

# Cleanup .profile
if [ -f "$HomePath"/.profile.dh ]; then
 mv "$HomePath"/.profile.dh "$HomePath"/.profile
else
 for i in "DigiHub"  "sysinfo"; do
  if grep -qF "$i" "$HomePath"/.profile; then
   sed -i "/$i/d" "$HomePath"/.profile
  fi
 done
fi 

# Remove whitespace from .profile
perl -i.bak -0777 -pe 's{\s+\z}{}m' ~/.profile >/dev/null 2>&1
printf '\n' >> "$HomePath"/.profile
rm "$HomePath"/.profile.bak*

# Remove configuration file
 rm "$HomePath"/.dhinfo*
 
# Remove Directories
sudo rm -rf "$DigiHub"

# Remove Packages

# Reboot
while true; do
 printf '\nReboot Now (Y/n) '; read -n1 -r response
 case $response in     Y|y) printf '\nRebooting\n'; break ;; N|n) printf '\nA reboot is required to completely remove DigiHub.\n\n'; break ;; *) printf '\nInvalid response, please select Y/n' ;; esac
done

