#!/usr/bin/env bash

: <<'END'
dwsetup
Direwolf installer and updater

Version 1.0a

Steve de Bode - KQ4ZCI - December 2025
END

cd $HomePath
git clone https://www.github.com/wb2osz/direwolf
cd direwolf
mkdir build && cd build
cmake ..
make -j4
sudo make install
make install-conf

cd $HomePath
rm -r direwolf 
