#!/bin/bash

#
# editconfig
# DigiHub Configuration Editor
#
# Version 1.0a
#
# Steve de Bode - KQ4ZCI - December 2025
#


# Remeber changes in .profile might be needed in venv/bin/activate

DigiHubGPSport
DigiHubcall
DigiHubaprs #APRS Password
DigiHubLat
DigiHubLon
DigiHubgrid