#!/bin bash

#
# gpsposition
# python script wrapper for gpsposition.py
#
# Version 1.0a
#
# Steve de Bode - KQ4ZCI - December 2025
#

source "$DigiHubvenv/bin/activate"
coordinates=$(python3 $DigiHubPy/coordinates.py)
IFS=',' read -r lat lon <<< "$coordinates"
deactivate

printf  '\n Current Location: Latitude: %s Longitude: %s\n\n' "$lat" "$lon"
