#!/bin/bash

: <<'END'
hamgrid
python script wrapper for hamgrid.py

Version 1.0a

Steve de Bode - KQ4ZCI - December 2025

Input:	latitude Longitude
Output: Formatted grid
END

# Check Parameters
if [ "$#" -ne "2" ]; then
  printf '\nIncorrect syntax\n\n %s <Latitude> <Longitude>\n\n' "${0##*/}" >&2
  exit 1
fi

hamgrid=$($DigiHubPy/hamgrid.py "$1" "$2")

printf  '\nThe Maidenhead Grid Square for Latitude %s, Longitude %s is: %s\n\n' "$1" "$2" "$hamgrid"
