#!/bin/bash

#
# uninstall
# DigiHub uninstallation
#
# Version 1.0a
#
# Steve de Bode - KQ4ZCI - December 2025
#


#warning

# sudo rm -r $DigiHub

# sudo apt -y purge 

# Remove Environment & PATH
for i in "DigiHub"  "export venv_dir" "export Callsign" "export APRSPass" "export Lat" "export Lon" "export Grid" "sysinfo"; do
 if grep -qF "$i" "$HomePath/.profile"; then
  sed -i "/$i/d" "$HomePath/.profile"
 fi
done
