#!/usr/bin/env bash

: <<'END'
whohami
read and print curent user information from ~/.dhinfo
Linux users should get the pun!

Version 1.0a

Steve de Bode - KQ4ZCI - December 2025

Input:	none
Output: none - informational
END

colb='\033[34m'; ncol='\e[0m'

IFS=',' read -r callsign class expiry grid lat lon licstat forename initial surname suffix street town state zip country < "/home/$USER/.dhinfo"

fullname="$forename $initial $surname $suffix"; fullname=$(echo "$fullname" | xargs)
address="$street, $town, $state $zip $country"
address="${address##[ ,]*}"

if [[ "$class" == "?" && "$grid" == "?" ]]; then class="U"; licstat="U"; fi

# Convert License Class
case "$class" in "T") class="Technician" ;; "G") class="General" ;; "E") class="Extra" ;; "N") class="Novice" ;; "A") class="Advanced" ;; "U") class="?" ;; *) class="Unknown/Station Callsign" ;; esac

# Convert License Status
case "$licstat" in "A") licstat="Active" ;; "E") licstat="Expired" ;; "P") licstat="Pending" ;; "U") licstat="?" ;; *) licstat="Unknown" ;; esac

printf '%b' '\nThe details for this installation of DigiHub for callsign ' "$colb" "$callsign" "$ncol" ' are:\n\n'
printf 'License:\t%s - Expiry %s (%s)\nName:\t\t%s\nAddress:\t%s\nCoordinates:\tGrid: %s Latitude: %s Longitude: %s\n\n' "$class" "$expiry" "$licstat" "$fullname" "$address" "$grid" "$lat" "$lon"