#! /bin/bash

#
# checkcall
# Get FCC Information by HAM Callsign
#
# Version 1.0a
#
# Steve de Bode - KQ4ZCI - December 2025
#

# Check Parameters
if [ "$#" -ne "1" ]; then
  printf '\nIncorrect syntax\n\n %s <callsign>\n\n' "${0##*/}" >&2
  exit 1
fi

# Get Home QTH & Check Valid
qth=$(curl -s "https://api.hamdb.org/v1/$1/csv/$1")
IFS=',' read -r callsign licenseclass licenseexpiry grid lat lon status forename initial surname suffix street town state zipcode country <<< "$qth"

if [ "$callsign" != "${1^^}" ]; then
 printf '\nThe Callsign \"%s\" is either invalid or not found, please check and try again.\n\n' "$1"
 exit 1
fi

fullname="$forename $initial $surname $suffix"; fullname=$(echo "$fullname" | xargs)
address="$street, $town, $state $zipcode $country"

# Convert License Class
case "$licenseclass" in
 "T")
  licenseclass="Technician"
  ;;
 "G")
  licenseclass="General"
  ;;
 "E")
  licenseclass="Extra"
  ;;
 "N")
  licesnseclass="Novice"
  ;;
  "A")
  licenseclass "Advanced"
  ;;
 *)
  licenseclass="Station Callsign"
  ;;
esac

# Convert License Status
case "$status" in
 "A")
  status="Active"
  ;;
 "E")
  status="Expired"
  ;;
 "P")
  status="Pending"
  ;;
 *)
  status="Unknown"
  ;;
esac

printf '\nThe details held by the FCC for %s are:\n\n' "$callsign"
printf 'License:\t%s - Expiry %s (%s)\nName:\t\t%s\nAddress:\t%s\nCoordinates:\tGrid: %s Latitude: %s Longitude %s\n\n' "$licenseclass" "$licenseexpiry" "$status" "$fullname" "$address" "$grid" "$lat" "$lon"
